server:
  port: 8191



spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DilshanLiyanage/microservices-skeleton-configs.git
          search-paths:
            - '*service'
          username: ${AC_CONFIG_SERVICE_GIT_REMOTE_USER}
          password: ${AC_CONFIG_SERVICE_GIT_REMOTE_PASSWORD}
          passphrase: ${AC_CONFIG_SERVICE_GIT_REMOTE_PASSPHRASE}
          skip-ssl-validation: true
          timeout: 10
  application:
    name: CONFIG-SERVER


